### ISSUE TITLE
I propose we use U-Bus instead of D-Bus. Here's why

### ISSUE THREAD

**Issue by xplshn** [chimera-linux/dinit-dbus#1]
### Introduction
Ubus is an RPC tool of OpenWRT, a micro system bus architecture. The aim of Ubus is to provide system-level Inter-process Communication(IPC) for various background processes and applications. Ubus is basically consistent with D-Bus in the design conception, providing system-level bus function. In order to be compatible with constrained environment says embedded systems, ubus reduced memory footprint
Provide various daemons and applications with IPC(Inter-process Communication) service.
Work as a broker, forward messages between related application(s) in different ways.
Several tools are invented for accessing UBUS

-     libubus: a library for software to access UBUS.
-     Cmd-line ubus tool.
-     Ubus Lua module

#### Command-line ubus tool

The ubus command line tool allows to interact with the ubusd server (with all currently registered services). It's useful for investigating/debugging registered namespaces as well as writing shell scripts. For calling procedures with parameters and returning responses it uses the user-friendly JSON format. Below is an explanation of its commands.

#### IPC

Inter-process Communication refers to mechanism allowing processes to manage shared data. There are different approaches to IPC tailored to different software requirements, says performance, modularity, network bandwidth and latency.
Examples of IPC method:

-     File
-     Signal
-     Socket / Unix domain Socket
-     Shared memory
Most of IPC methods use client-server model to share data between processes.
# ![https://imgur.com/J6xt4J6.png](https://imgur.com/J6xt4J6.png)

While there are m servers, and each server has nk clients. The number of IPC connections in client/server model is:
### m∑k=1nk

....
The original technical specs are here: https://hackmd.io/@rYMqzC-9Rxy0Isn3zClURg/H1BY98bRw and here: https://openwrt.org/docs/techref/ubus

It is compatible with the Dbus specification, it is used in OpenWRT, works in Musl, can be statically compiled, and is MUCH, MUCH reliable than Dbus. I'd really love to see more OSes implementing it.

##### Repos are here:
https://git.openwrt.org/?p=project/ubus.git;
MIRROR: https://github.com/openwrt/ubus

I really hope this can be taken into serious consideration.

**Comment by q66** [comment]
okay, except i don't care because this is meant for d-bus

**Comment by xplshn** [comment]
No need to be so rude.

**Comment by q66** [comment]
considering the whole point of this repo is to provide integration for d-bus so that d-bus-using services can perform their activation through dinit, coming into the issue tracker and infodumping something about different software that has nothing to do with the task at hand and does not even remotely achieve anything related to the task is more than just unhelpful, and i don't know what else to tell you

**Comment by xplshn** [comment]
Okay, then, sorry to bother then, but where shall I do so? Where's the main repo?
